### ISSUE TITLE
Resetting view position with zoom 

### ISSUE THREAD

**Issue by Cayan** [PeterStaev/nativescript-image-swipe#1]
I'm using a NAN application and whenever I have a zoomed image and moves around it, if I touch the screen again, I can't keep moving it around in the screen it will be reseted to x = 0 and y = 0

**Comment by PeterStaev** [comment]
Hey @Cayan , I've just tried both iOS and Android in the sims with the demo project in this report, and i cannot simulate this behavior.

**Comment by PeterStaev** [comment]
No further response so closing this one for now. In case you still have problems, please reopen and provide more details.

**Comment by ghost** [comment]
@Cayan I have the same issue, did you solve it?

**Comment by hypertenso** [comment]
Looking at the code from the `image-swipe.android.js` file, I could see that some actions reset the position of the image. From line **217** to **220** we have this code snippet:
```
    ZoomImageView.prototype.setImageBitmap = function (image) {
        this._image = image;
        this.reset();
    };
```

I removed line **219** (`this.reset ()`) and the image stopped resetting the position. The problem now is to zoom in on the place where I'm touching the screen, currently the zoom occurs on the left side of the screen, rather than in the place where I'm touching.

**Comment by ghost** [comment]
I realized that the image resets the position if I drag my fingers fast on the screen. If I move slowly, the problem does not happen. It seems to me that the plugin confuses the swipe action with the zoom action when you make quick movements.

**Comment by Cayan** [comment]
I gave up, I'll probably try to implement this again soon.
