### ISSUE TITLE
Double tap to clear zoom

### ISSUE THREAD

**Issue by Cayan** [PeterStaev/nativescript-image-swipe#2]
A common feature for image viewers is that whenever you have some zoom if you double tap it is gonna reset the zoom

**Comment by davecoffin** [comment]
This would be amazing. Started to look into it but a lot is over my head.
This is where I started: https://stackoverflow.com/questions/3967971/how-to-zoom-in-out-photo-on-double-tap-in-the-iphone-wwdc-2010-104-photoscroll
@PeterStaev my current thoughts are to call `setZoomScaleAnimated` in UIScrollView on iOS on a double tap on the container. I tried that by just doing 
`gallery.ios.setZoomScaleAnimated(5, true);`
but it doesnt work. No errors and the method `gallery.ios.setZoomScaleAnimated` does exist, but the photo doesnt scroll. Thoughts?

**Comment by PeterStaev** [comment]
@davecoffin , it is not that simple. The root scroll view is just for navigating between images. Then inside the this one there is another one that is for zooming:
https://github.com/PeterStaev/nativescript-image-swipe/blob/9ea9613d89f688ddfcc63db2bf04ad149803279b/image-swipe.ios.ts#L201-L207

So in order to zoom, you have to get instance of the `zoomScrollView` for the given page and use that method on it.

**Comment by davecoffin** [comment]
Ok that makes perfect sense. I am really close here, but I just need to confirm a few things.
- As you swipe through the gallery, new UIViews (containing the zoomScrollView) are *appended* to the top level scrollview, right? If I am understanding it correctly, when you tap an image and open the gallery, there are 3 "pages" loaded, so the UIScrollView will have 3 UIViews and subviews..the current page, the one behind and the one ahead. So my question is, how can I accurately get the zoomScrollView that is displayed? I have it working for the current page when you first open the gallery like this:
```
var gallery = frameModule.topmost().getViewById('gallery');
setTimeout(function() {
  if (gallery.ios.subviews && gallery.ios.subviews[0] && gallery.ios.subviews[0].subviews && gallery.ios.subviews[0].subviews[1]) {
    zoomScrollView = gallery.ios.subviews[0].subviews[1];
  }
}, 300)
```
That works but I obviously need a way to determine which subview is the one being displayed so I can set the reference to it and call `setZoomScaleAnimated` on the correct UIScrollView. I am setting the reference to the first zoomScrollView and not changing it, so if you swipe to a new image and double tap, it zooms in on the previous page haha. Check it out: 
https://cl.ly/tK6D

- One other question, do you know how to determine if a UIScrollView is zoomed in? Theres a delegate method to hook into (`scrollViewDidEndZoomingWithViewAtScale`), but at the moment I am trying to accomplish this in my project before I attempt to contribute to the plugin. accessing zoomScale just returns 1 all the time. I am currently doing it by seeing if `zoomScrollView.contentOffset.x > 0 || zoomScrollView.contentOffset.y > 0` but that will be true if you are zoomed in AND panned to the top left corner. 

Any help is greatly appreciated! Once I get this working I plan on contributing and adding a double tap event

**Comment by PeterStaev** [comment]
@davecoffin , try to use `imageSwipe._views` private property. This is an array that should contain properties for the pages:
https://github.com/PeterStaev/nativescript-image-swipe/blob/9ea9613d89f688ddfcc63db2bf04ad149803279b/image-swipe.ios.ts#L24
So using `imageSwipe._views[page]` (where `page` is your current page) should get you the object of the current page. From there in order to get the zoom view you can use `imageSwipe._views[page].imageView.superview`

As for how to get the current scale, using the `zoomScale` property of the `UIScrollView` should do the trick: https://developer.apple.com/documentation/uikit/uiscrollview/1619419-zoomscale?language=objc

**Comment by davecoffin** [comment]
OMG amazing that worked like a dream. I got double tapping working 🎉 Ok so one last question...the zoomScale is reporting unexpected results. It looks like when a photo is zoomed all the way in, the zoomScale is 1. But when its zoomed all the way out its not 0, it depends on the photo. I'm getting like .25, .3333 etc for photos that are zoomed all the way out. Any idea why?

**Comment by davecoffin** [comment]
I think I understand whats happening, the images are actually being displayed at more than 0 zoomScale in order to take up the full width of the device. I think I'll need to capture the initial zoomScale in a map or something.

**Comment by PeterStaev** [comment]
`zoomScale` shows you how much the image is zoomed inside the scrollview. In most cases when you actually show photos this will be less than 1 so that the image fits on the screen. If it is 1 this means that the image is displayed 1:1 on the screen. It can never be 0 as then this means that the image is not shown. 

No need to create a map as the plugin already has internally the "fit" zoom: 
https://github.com/PeterStaev/nativescript-image-swipe/blob/9ea9613d89f688ddfcc63db2bf04ad149803279b/image-swipe.ios.ts#L264-L268
So if you want to reset zoom simply use the `zoomScrollView`'s `minimumZoomScale` prop 😄

**Comment by davecoffin** [comment]
So my problem is id like to know if an image is zoomed in at all. But when a photo is loaded, the zoomScale is neither 0 nor 1 but somewhere in between. When a photo is zoomed in as far as it can go, the zoomScale is 1. The reason I need to know if its zoomed in is because for example if you pinch to zoom in and *then* double tap, it should zoom out. So at the point the user double taps, I need to know if the photo is zoomed in at all. I thought I could determine this by evaluating if zoomScale > 1, but zoomScale always has the image somewhere between 0 and 1.

**Comment by PeterStaev** [comment]
The image is zoomed if `zoomScrollView.zoomScale !== zoomScrollView.minimumZoomScale` 😉

**Comment by davecoffin** [comment]
Dude you rock. 1000% respect. Everything is working like a charm.

**Comment by PeterStaev** [comment]
This is now available in the new version of the plugin available in the [ProPlugins NPM](https://npm.proplugins.org) registry. 

All future work of this plugin will be available exclusively as part of ProPlugins initiative. So if you want to get the latest updates/fixes/features make sure you [subscribe to the service](https://proplugins.org/subscribe.html). You get all my plugins plus many of the most used and high quality plugins for a small monthly subscription fee.

**Comment by davecoffin** [comment]
Thanks @PeterStaev you rock!
