### ISSUE TITLE
Cannot read property 'setScaleFactor' of null

### ISSUE THREAD

**Issue by san3k1990** [PeterStaev/nativescript-image-swipe#52]
Sometimes i get an error `Cannot read property 'setScaleFactor' of null`, when I try to enlarge a picture. This is Error on Android.

```
StackTrace:
    Frame: function:'onScale', file:'file:///node_modules\nativescript-image-swipe\image-swipe.js:212:0
   Frame: function:'ZoomImageView.onTouchEvent', file:'file:///node_modules\nativescript-image-swipe\image-swipe.js:295:0
   at com.tns.Runtime.callJSMethodNative(Native Method)
...
```

**Comment by PeterStaev** [comment]
This should be fixed in the new version of the plugin available in the [ProPlugins NPM](https://npm.proplugins.org) registry. 

All future work of this plugin will be available exclusively as part of ProPlugins initiative. So if you want to get the latest updates/fixes/features make sure you [subscribe to the service](https://proplugins.org/subscribe.html). You get all my plugins plus many of the most used and high quality plugins for a small monthly subscription fee.
